sonar.projectKey=doljak-projects_drupal-basic
sonar.organization=doljak-projects
sonar.projectName=Waggy Pet Shop — Drupal 11

sonar.sources=web/modules/custom,web/themes/custom
sonar.exclusions=**/vendor/**,**/node_modules/**,**/tests/**
sonar.php.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
