name: 'CI Basic'

on:                                                                                                                                                                                               
  push:                                                                                                                                                                                           
    branches:                                                                                                                                                                                     
      - 'feat/*'
      - 'refactor/*'
      - 'chore/*'

jobs:
  build:
    runs-on: ubuntu-latest                                                                                                                                                                        
    steps:
      - name: Checkout                                                                                                                                                                            
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup PHP
        uses: shivammathur/setup-php@690cb7c9d81dbfe51eba732cfca0a00ca42db777
        with:                                                                                                                                                                                     
          php-version: '8.4'
          tools: composer:v2.9.5                                                                                                                                                                  
          extensions: mbstring, xml, curl
                                                                                                                                                                                                  
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist                                                                                                                                      
                
      - name: Lint
        run: find web/modules/custom web/themes/custom -name "*.php" | xargs php -l